#!/bin/bash

rm -rf /var/www/* /var/www/.*
mysql --host=db --port=3306 --user=my_user --password=my_pass --database=my_database --execute="SHOW TABLES" -s | xargs -I "@@" mysql --host=db --port=3306 --user=my_user --password=my_pass --database=my_database --execute="DROP TABLE @@"
